### ISSUE TITLE
Bank Account addition?

### ISSUE THREAD

**Issue by jeffAwesome** [function/Forte-ActiveMerchant#2]
I didn't see anything related to adding bank accounts instead of credit cards. Is this a possibility moving forward?

Update: I did notice some information about e checks in this file 

https://github.com/function/Forte-ActiveMerchant/blob/active_merchant-gateway-interface/lib/active_merchant/billing/gateways/forte/web_service_authentication.rb

I'll be playing around with it, just wanted to see if this was supported before investing too much time.

**Comment by TheKidCoder** [comment]
We can tokenize bank accounts by doing this:
```ruby
create_payment_method(payment_type: :bank_account, ...)
```

Then use the params described here: https://github.com/function/Forte-ActiveMerchant/blob/active_merchant-gateway-interface/lib/active_merchant/billing/gateways/forte/web_service_authentication.rb#L120
